# Generated by Django 5.2.15 on 2026-07-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_contact_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
