# Generated by Django 5.2.15 on 2026-08-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_contact_last_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="company",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="source",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[("lead", "Lead"), ("customer", "Customer")],
                default="lead",
                max_length=20,
            ),
        ),
    ]
